name: Lab 1 pipeline

on:
  pull_request:
    branches:
      - trunk  # Some svn-style naming convention here, svn sucks ass
      - lab1
  push:
    branches:
      - lab1

jobs:
  lint:
    runs-on: ubuntu-latest  # Use Ubuntu to run clang-format for linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: clang-format --dry-run --Werror --verbose $(find . -name '*.cpp' -or -name '*.hpp')