name: Lab 1 pipeline

on:
  pull_request:
    branches:
      - trunk  # Some svn-style naming convention here, svn sucks ass
      - lab1
  push:
    branches:
      - lab1

jobs:
  # Step 1: Lint the code with clang-format and clang-tidy in ./source and ./test
  lint:
    runs-on: ubuntu-latest  # Use Ubuntu to run linting tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang tools
        run: sudo apt-get install -y clang-format clang-tidy

      - name: Install Google Test
        run: |
          sudo apt-get install -y libgtest-dev && \
          sudo cmake -S /usr/src/googletest -B /usr/src/googletest/build && \
          sudo cmake --build /usr/src/googletest/build && sudo cp /usr/src/googletest/build/lib/*.a /usr/lib

      - name: Format code with clang-format
        run: |
          find ./source ./test -name '*.cpp' -or -name '*.hpp' | xargs clang-format -i

      - name: Verify clang-format
        run: |
          if ! clang-format --dry-run --Werror $(find ./source ./test -name '*.cpp' -or -name '*.hpp'); then
          echo "Code is not properly formatted!"
          exit 1
          fi

      - name: Run clang-tidy on ./source and ./test
        run: |
          clang-tidy $(find ./source ./test -name '*.cpp' -or -name '*.hpp') \
          -- -std=c++17 \
          -I./source \
          -I./test \
          -I/usr/src/googletest/include \
          -header-filter='^/home/runner/work/diy-shell-benchmark-24y-Vad1mChK/diy-shell-benchmark-24y-Vad1mChK/(source|test)'