name: Lab 1 pipeline

on:
  pull_request:
    branches:
      - trunk  # Some svn-style naming convention here, svn sucks ass
      - lab1
  push:
    branches:
      - lab1

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clang
        run: choco install llvm -y

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run C++ Lint
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse -Include *.cpp, *.h | ForEach-Object { $_.FullName }
          foreach ($file in $files) {
            & "C:\Program Files\LLVM\bin\clang-tidy.exe" $file -p build/
          }
